### ISSUE TITLE
run nightly

### ISSUE THREAD

**Issue by adriaanm** [scala/compiler-benchmark#40]
I hope I haven't missed the existing ticket somewhere else. JB would really like this to happen soon.

**Comment by lrytz** [comment]
i guess he means to run the "scala" benchmark nightly, since we run the others mergely. i'll take a look.

**Comment by adriaanm** [comment]
Thanks

**Comment by lrytz** [comment]
https://scala-ci.typesafe.com/benchq/benchmarks - benchmarks can now be made run at most every n days

i'll monitor things to see if everything works as intended.

**Comment by lrytz** [comment]
I merged some PRs, seems to work as expected so far.
