### ISSUE TITLE
A way to pass extra arguments (more than one)

### ISSUE THREAD

**Issue by dragos** [scala/compiler-benchmark#42]
I tried `-p extraArgs=-nowarn` and that works, but I can't pass more than one argument, neither in any kind of quotes nor without. I couldn't find where I could fix this either :(

**Comment by lrytz** [comment]
I think `|`-separated works: https://github.com/scala/compiler-benchmark/blob/master/compilation/src/main/scala/scala/tools/nsc/ScalacBenchmark.scala#L16. I just updated the readme (https://github.com/scala/compiler-benchmark/commit/eec0a5a9d678d632782bdffc90700fc62d1eb895). Please re-open if that doesn't work.
