### ISSUE TITLE
Provide some example results

### ISSUE THREAD

**Issue by david-bouyssie** [scala/compiler-benchmark#8]
I think that it could be great to provide some example results for the major scala versions (2.10, 2.11, 2.12).
It would be also nice to link these results to the following question:
https://www.quora.com/How-fast-is-the-current-compiler-for-Scala-compared-to-Java-Do-you-think-it-will-be-faster-for-Scala-2-12

Thanks !

**Comment by retronym** [comment]
We (the Scala team at Lightbend) are currently working on automatically collecting and visualizing benchmark results from this repo.

Here's a sneak preview, currently showing the steady improvement of the time a wamed-up JVM taks to to compile the `scalap` sources over time: https://scala-ci.typesafe.com/grafana/dashboard/db/scala-benchmark

**Comment by retronym** [comment]
It would be interesting to find a non-trivial program that was translated verbatim from Java to to Scala so we could do a fair comparative benchmark of javac and scalac. I haven't been able to find such a corpus yet.

**Comment by david-bouyssie** [comment]
Very nice UI :D

I was not aware of this project, you should advertise it !

Thank you !

**Comment by retronym** [comment]
Blog post coming next week; we've regenerated the data on a stable machine an polished up the presentation/usability of the charts: https://scala-ci.typesafe.com/grafana/dashboard/db/scala-benchmark
